enum class EChatNoticeType {
    Normal = (0),
    Campaign = (1),
    Emergency = (2),
    Tip = (3),
    GuildBoss = (4),
    OfferingCarrier = (5),
    Defence = (6),
    KeepNotify = (7),
    ClearKeepNotify = (8),
    Hunting = (9),
    HuntingEnd = (10),
    Kzarka = (11),
    Nuberu = (12),
    FieldBoss = (13),
    PvPHost = (14),
    SavageDefence = (15),
    SavageDefenceBoss = (16),
    None = (15)
};