enum class EItemClassify {
    Etc = (0),
    MainWeapon = (1),
    SubWeapon = (2),
    Armor = (3),
    Accessory = (4),
    BlackStone = (5),
    Jewel = (6),
    Potion = (7),
    Cook = (8),
    PearlGoods = (9),
    Housing = (10),
    Vehicle = (11),
    Mine = (12),
    Wood = (13),
    Seed = (14),
    Leather = (15),
    Fish = (16),
    DyeAmpule = (17)
};